// generated by fetch-trending.mjs — top non-crypto, non-stablecoin tokenized assets by 24h volume
window.TRENDING_DATE = "July 10th, 2026";
window.TRENDING_YEAR = "2026";
window.TRENDING = [
  {
    "rank": 1,
    "symbol": "MU",
    "name": "Micron",
    "logo": "assets/logo1.png",
    "priceText": "$988.58",
    "volText": "$10.6M",
    "changeText": "-2.62%",
    "up": false
  },
  {
    "rank": 2,
    "symbol": "SNDK",
    "name": "SanDisk",
    "logo": "assets/logo2.svg",
    "priceText": "$1,921",
    "volText": "$9.7M",
    "changeText": "-0.65%",
    "up": false
  },
  {
    "rank": 3,
    "symbol": "CRCL",
    "name": "Circle",
    "logo": "assets/logo3.png",
    "priceText": "$66.23",
    "volText": "$9.4M",
    "changeText": "+3.73%",
    "up": true
  },
  {
    "rank": 4,
    "symbol": "SPY",
    "name": "SP500",
    "logo": "assets/logo4.png",
    "priceText": "$754.07",
    "volText": "$5.6M",
    "changeText": "+0.48%",
    "up": true
  }
];
