// generated by fetch-trending.mjs — top assets by 24h volume
window.TRENDING_DATE = "June 17th, 2026";
window.TRENDING_YEAR = "2026";
window.TRENDING = [
  {
    "rank": 1,
    "symbol": "SPCX",
    "name": "SpaceX",
    "logo": "assets/logo1.svg",
    "priceText": "$197.90",
    "volText": "$99.5M",
    "changeText": "-7.15%",
    "up": false
  },
  {
    "rank": 2,
    "symbol": "HYPE",
    "name": "HYPE",
    "logo": "assets/logo2.png",
    "priceText": "$74.35",
    "volText": "$66.1M",
    "changeText": "+0.27%",
    "up": true
  },
  {
    "rank": 3,
    "symbol": "cbBTC",
    "name": "Coinbase BTC",
    "logo": "assets/logo3.png",
    "priceText": "$65,383",
    "volText": "$46.7M",
    "changeText": "-0.92%",
    "up": false
  },
  {
    "rank": 4,
    "symbol": "wETH",
    "name": "Ether",
    "logo": "assets/logo4.png",
    "priceText": "$1,769",
    "volText": "$20.7M",
    "changeText": "-1.70%",
    "up": false
  }
];
