// generated by fetch-trending.mjs — top tokenized stocks by 24h volume
window.TRENDING_DATE = "July 9th, 2026";
window.TRENDING_YEAR = "2026";
window.TRENDING = [
  {
    "rank": 1,
    "symbol": "MU",
    "name": "Micron",
    "logo": "assets/logo1.png",
    "priceText": "$1,013",
    "volText": "$14.8M",
    "changeText": "+7.62%",
    "up": true
  },
  {
    "rank": 2,
    "symbol": "SPCX",
    "name": "SpaceX",
    "logo": "assets/logo2.svg",
    "priceText": "$153.13",
    "volText": "$9.2M",
    "changeText": "+5.22%",
    "up": true
  },
  {
    "rank": 3,
    "symbol": "SNDK",
    "name": "Sandisk",
    "logo": "assets/logo3.svg",
    "priceText": "$1,931",
    "volText": "$8.1M",
    "changeText": "+15.71%",
    "up": true
  },
  {
    "rank": 4,
    "symbol": "NVDAx",
    "name": "NVIDIA",
    "logo": "assets/logo4.png",
    "priceText": "$203.78",
    "volText": "$2.7M",
    "changeText": "+0.39%",
    "up": true
  }
];
